"""empty message

Revision ID: 21e247f8c032
Revises: ed8fede3e8cc
Create Date: 2021-02-23 23:20:59.238409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e247f8c032'
down_revision = 'ed8fede3e8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'idea', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'learn', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'type_table', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'type_table', type_='foreignkey')
    op.drop_constraint(None, 'learn', type_='foreignkey')
    op.drop_constraint(None, 'idea', type_='foreignkey')
    # ### end Alembic commands ###
