"""empty message

Revision ID: 28c16ce1de72
Revises: ed8fede3e8cc
Create Date: 2021-02-21 14:31:12.485913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c16ce1de72'
down_revision = 'ed8fede3e8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'idea', 'user', ['user_id'], ['id'])
    op.add_column('learn', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'learn', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'learn', type_='foreignkey')
    op.drop_column('learn', 'user_id')
    op.drop_constraint(None, 'idea', type_='foreignkey')
    op.drop_column('idea', 'user_id')
    # ### end Alembic commands ###
