"""empty message

Revision ID: 35c1c83db188
Revises: d0a34b9c407f
Create Date: 2020-06-01 11:41:05.554936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c1c83db188'
down_revision = 'd0a34b9c407f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('event', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('extra', sa.String(length=200), nullable=True),
    sa.Column('ip', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_event'), 'audit_log', ['event'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
