"""empty message

Revision ID: 46c038778835
Revises: 5aa47c478c7b
Create Date: 2021-02-16 16:00:36.170384

"""
from alembic import op
import sqlalchemy as sa
from agile.database import JSONstore


# revision identifiers, used by Alembic.

revision = '46c038778835'
down_revision = '5aa47c478c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('extra', JSONstore(), nullable=True))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_column('audit_log', 'extra')
    # ### end Alembic commands ###
