"""empty message

Revision ID: 5aa47c478c7b
Revises: 08f772624934
Create Date: 2021-02-16 15:06:00.068609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa47c478c7b'
down_revision = '08f772624934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=32), nullable=False))
    op.drop_constraint('user_name_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
