"""empty message

Revision ID: 6ed6b0f89833
Revises: ec7159f46381
Create Date: 2021-02-17 18:02:03.338167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed6b0f89833'
down_revision = 'ec7159f46381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_table', 'name_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_table', sa.Column('name_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
