"""empty message

Revision ID: 912f332fc005
Revises: 786befd0e84b
Create Date: 2021-02-19 18:58:40.577548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912f332fc005'
down_revision = '786befd0e84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'idea_name', 'type_table', ['name_id'], ['id'])
    op.create_foreign_key(None, 'idea_type', 'details_table', ['type_id'], ['id'])
    op.create_foreign_key(None, 'learn_name', 'type_table', ['name_id'], ['id'])
    op.create_foreign_key(None, 'learn_type', 'details_table', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'learn_type', type_='foreignkey')
    op.drop_constraint(None, 'learn_name', type_='foreignkey')
    op.drop_constraint(None, 'idea_type', type_='foreignkey')
    op.drop_constraint(None, 'idea_name', type_='foreignkey')
    # ### end Alembic commands ###
