"""empty message

Revision ID: c2ef9dfb9585
Revises: 6ed6b0f89833
Create Date: 2021-02-17 18:04:25.314137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ef9dfb9585'
down_revision = '6ed6b0f89833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_table', sa.Column('name_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_table', 'name_id')
    # ### end Alembic commands ###
