"""empty message

Revision ID: 9d15353b9917
Revises: 
Create Date: 2020-04-02 10:58:22.861970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0a34b9c407f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=164), nullable=True),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("brandCode", sa.String(length=10), nullable=True),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "brand",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=164), nullable=True),
        sa.Column("code", sa.String(length=10), nullable=True),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "category",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("group", sa.String(length=50), nullable=True),
        sa.Column("code", sa.String(length=3), nullable=True),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "concept_programme",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=15), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=15), nullable=True),
        sa.Column("brandUrl", sa.String(length=50), nullable=True),
        sa.Column("packingUrl", sa.String(length=50), nullable=True),
        sa.Column("backgroundUrl", sa.String(length=50), nullable=True),
        sa.Column("generatedP", sa.Boolean(), nullable=True),
        sa.Column("generatedI", sa.Boolean(), nullable=True),
        sa.Column("cLocation", sa.String(length=50), nullable=True),
        sa.Column("pLocation", sa.String(length=50), nullable=True),
        sa.Column("iLocation", sa.String(length=50), nullable=True),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "department",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=164), nullable=True),
        sa.Column("default", sa.Boolean(), nullable=True),
        sa.Column("bases_test_quota", sa.Integer(), nullable=True),
        sa.Column("pred_idea_quota", sa.Integer(), nullable=True),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_department_default"), "department", ["default"], unique=False
    )
    op.create_table(
        "packing",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=164), nullable=True),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("brandCode", sa.String(length=10), nullable=True),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=164), nullable=True),
        sa.Column("default", sa.Boolean(), nullable=True),
        sa.Column("permissions", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_default"), "role", ["default"], unique=False)
    op.create_table(
        "bases_file",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=80), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "concept_idea",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("benefit", sa.String(length=15), nullable=True),
        sa.Column("ingredient", sa.String(length=15), nullable=True),
        sa.Column("category", sa.String(length=15), nullable=True),
        sa.Column("demand_space", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("oHypothesis", sa.String(length=500), nullable=False),
        sa.Column("smoothness", sa.Float(), nullable=False),
        sa.Column("hypothesis", sa.String(length=500), nullable=True),
        sa.Column("isBatch", sa.Boolean(), nullable=True),
        sa.Column("isIdea", sa.Boolean(), nullable=True),
        sa.Column("data", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=50), nullable=True),
        sa.Column("brandName", sa.String(length=20), nullable=True),
        sa.Column("conceptProgrammeId", sa.String(length=15), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["conceptProgrammeId"], ["concept_programme.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "department_category",
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"]),
        sa.ForeignKeyConstraint(["department_id"], ["department.id"]),
        sa.PrimaryKeyConstraint("department_id", "category_id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=80), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("is_supervisor", sa.Boolean(), nullable=False),
        sa.Column("is_adal", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["department_id"], ["department.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "pred_idea",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idea_no", sa.String(length=80), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("brand", sa.String(length=500), nullable=True),
        sa.Column("format", sa.String(length=500), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.String(length=2000), nullable=False),
        sa.Column("brand_en", sa.String(length=500), nullable=True),
        sa.Column("title_en", sa.String(length=500), nullable=True),
        sa.Column("content_en", sa.String(length=2000), nullable=True),
        sa.Column("keywords", sa.String(), nullable=True),
        sa.Column("ai_prediction", sa.JSON(), nullable=True),
        sa.Column("bases_test", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("is_green", sa.Boolean(), nullable=False),
        sa.Column("bases_file_id", sa.Integer(), nullable=True),
        sa.Column("image_path", sa.String(length=500), nullable=True),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["bases_file_id"], ["bases_file.id"]),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idea_no"),
    )
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=36), nullable=False),
        sa.Column("token_type", sa.String(length=10), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    op.create_table(
        "bases_test_workflow",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pred_idea_id", sa.Integer(), nullable=False),
        sa.Column("approved_by_fk", sa.Integer(), nullable=True),
        sa.Column("finalized_by_fk", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.String(length=200), nullable=True),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["approved_by_fk"], ["user.id"]),
        sa.ForeignKeyConstraint(["finalized_by_fk"], ["user.id"]),
        sa.ForeignKeyConstraint(["pred_idea_id"], ["pred_idea.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    
    op.create_table('weibo_statistics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('datatype', sa.String(length=50), nullable=True),
        sa.Column('attribute', sa.String(length=100), nullable=True),
        sa.Column('month', sa.Date(), nullable=True),
        sa.Column('buzz', sa.Integer(), nullable=True),
        sa.Column('engagement', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
        sa.PrimaryKeyConstraint('id')
    )    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bases_test_workflow")
    op.drop_table("token_blacklist")
    op.drop_table("pred_idea")
    op.drop_table("user")
    op.drop_table("department_category")
    op.drop_table("concept_idea")
    op.drop_table("bases_file")
    op.drop_index(op.f("ix_role_default"), table_name="role")
    op.drop_table("role")
    op.drop_table("packing")
    op.drop_index(op.f("ix_department_default"), table_name="department")
    op.drop_table("department")
    op.drop_table("concept_programme")
    op.drop_table("category")
    op.drop_table("brand")
    op.drop_table("background")
    # ### end Alembic commands ###
