"""empty message

Revision ID: ec7159f46381
Revises: 46c038778835
Create Date: 2021-02-17 16:07:52.654358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7159f46381'
down_revision = '46c038778835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_table', 'name_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_table', sa.Column('name_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
